### ISSUE TITLE
HTML and CSS style issues

### ISSUE THREAD

**Issue by hellospec** [hellospec/mbc2-book-store#5]
There are few things about HTML style fundamental I would like to encourages.
## HTML
* Use 2 spaces indentation for HTML file
* Avoid more than one empty line between html tag
```html
<!-- don't -->
<body>


  <div class="content">

    <h1>Title</h1>
    <p>
  
     Example line 1

     Example line 2
    </p>
  </div>


</body>
```
```html
<!-- do -->
<body>
  <div class="content">
    <h1>Title</h1>
    <p>
      Example line 1
      Example line 2
    </p>
  </div>
</body>
```

* Avoid white space when assign tag attributes
```html
<!-- don't -->
<div class = "item" >Item 1</div>

<!-- do -->
<div class="item" >Item 1</div>
```

* Keep following your indentation rule
```html
<!-- don't -->
<div class="countries">
  <div>Thailand</d>
  <div>Singapore</d>
    <div>Malysia</d>
  <div>Laos</d>
</div>

<!-- do -->
<div class="countries">
  <div>Thailand</d>
  <div>Singapore</d>
  <div>Malysia</d>
  <div>Laos</d>
</div>
```
* 

## CSS
* Use 2 spaces for indentation
* Always have space before `{` and space after `:`
```css
/* don't */
.item{
  color:red;
  font-size:19px;
}

/* do */
.item {
  color: red;
  font-size: 19px;
}
```
* No space before `;`
```css
/* don't */
main{
    width: 100%   ;     
}

/* do */
main {
  width: 100%;
}
```

Although all above could be resolve by using tools like automatic formatter or code editor feature, it is better to make it into our habit.
